project:
  type: website
  output-dir: docs

website:
  title: "Blue Sky Sailboat"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: Posts

format:
  html:
    theme: cosmo
    toc: true
